privet_ailabs_pika_page:
    path: /ailabs/pika
    defaults: { _controller: privet.ailabs.controller_pika:execute }

privet_ailabs_pika_callback:
    path: /ailabs/pika/callback/{job_id}/{ref}/{action}
    methods: [POST]
    defaults: 
        _controller: privet.ailabs.controller_pika:callback 
        mode: 'post'
    requirements:
        job_id: \d+
        ref: "[a-zA-Z0-9]+"
        action: posted|reply    

privet_ailabs_claude_page:
    path: /ailabs/claude
    defaults: { _controller: privet.ailabs.controller_claude:execute }

privet_ailabs_gemini_page:
    path: /ailabs/gemini
    defaults: { _controller: privet.ailabs.controller_gemini:execute }

privet_ailabs_gemini_vision_page:
    path: /ailabs/gemini_vision
    defaults: { _controller: privet.ailabs.controller_gemini_vision:execute }

privet_ailabs_chatgpt_page:
    path: /ailabs/chatgpt
    defaults: { _controller: privet.ailabs.controller_chatgpt:execute }

privet_ailabs_dalle_page:
    path: /ailabs/dalle
    defaults: { _controller: privet.ailabs.controller_dalle:execute }

privet_ailabs_stablediffusion_page:
    path: /ailabs/stablediffusion
    defaults: { _controller: privet.ailabs.controller_stablediffusion:execute }

privet_ailabs_midjourney_page:
    path: /ailabs/midjourney
    defaults: { _controller: privet.ailabs.controller_midjourney:execute }

privet_ailabs_midjourney_callback:
    path: /ailabs/midjourney/callback/{job_id}/{ref}/{action}
    methods: [POST]
    defaults: 
        _controller: privet.ailabs.controller_midjourney:callback 
        mode: 'post'
    requirements:
        job_id: \d+
        ref: "[a-zA-Z0-9]+"
        action: posted|reply

privet_ailabs_scriptexecute_page:
    path: /ailabs/scriptexecute
    defaults: { _controller: privet.ailabs.controller_scriptexecute:execute }    

privet_ailabs_view_log_controller_page:
    path: /ailabs/log/{post_id}
    defaults: { _controller: privet.ailabs.controller_log:view_log  }    
    requirements:
        post_id: \d+
